In [25]:
import pyspark

#Creamos una sesion de spark
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max, row_number
from pyspark.sql.window import Window

#Creamos un objeto de spark session
spark = SparkSession.builder.appName("pysparkdf").getOrCreate()

In [43]:
spark.stop()

In [95]:
import requests
import datetime
import json
import pandas as pd
import numpy as np
from IPython.display import display, JSON
from stock_indicators import indicators
from quote import *
import os

In [63]:
local = r"C:\Users\CARLES\Documents\proyect_inversion" 
api_key = 'F700B7APDLY7KI8K'
symbols = ['MSFT', 'GOOG', 'AMZN', 'AAPL']

In [68]:
# INCREMENTAL FUNCTIONS
# Función para obtener la última fecha de actualización de un archivo JSON
def get_last_refreshed_date(file_path, symbol):
    
    file_path_symbol = f"{file_path}\\symbols\\{symbol}.json"

    with open(file_path_symbol, 'r') as file:
        data = json.load(file)

    return data['Meta Data']['3. Last Refreshed']

# Función para guardar la última fecha de actualización en un archivo JSON
def save_last_refreshed_date(file_path, date):
    with open(file_path, 'r') as file:
        data = json.load(file)
    data['Meta Data']['3. Last Refreshed'] = date
    with open(file_path, 'w') as file:
        json.dump(data, file)

In [77]:
# SYMBOLS PARAMETERS
interval_symbol = 'daily'
outputsize_symbol = 'full'
function_symbol = 'TIME_SERIES_DAILY'

for i in symbols:
    path = f"{local}\\symbols\\{i}.json"
    url = f"https://www.alphavantage.co/query?function={function_symbol}&symbol={i}&outputsize={outputsize_symbol}&apikey={api_key}"
    response = requests.get(url)
    data = response.json()

    if response.status_code == 200:
        # Verifica si el archivo ya existe y ciérralo si está abierto
        if os.path.exists(path):
            os.remove(path)

        with open(path, 'w') as file:
            json.dump(data, file)

        print("Los datos para", i, "se han guardado exitosamente en", path)
    else:
        print("Error al obtener los datos para", i, ". Código de estado:", response.status_code)

Los datos para MSFT se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\symbols\MSFT.json
Los datos para GOOG se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\symbols\GOOG.json
Los datos para AMZN se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\symbols\AMZN.json
Los datos para AAPL se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\symbols\AAPL.json

In [35]:
# TECHNICAL INDICATORS PARAMETERS
function = ['SMA', 'EMA']
symbols
interval = 'daily'
time_period = 14
series_type = 'open'

for i in symbols:
    for a in function:
        path = f"{local}\\technical_indicators\\{i}_{a}.json"
        url = f'https://www.alphavantage.co/query?function={a}&symbol={i}&interval={interval}&time_period={time_period}&series_type=open&apikey={api_key}'
        response = requests.get(url)
        data = response.json()

        if response.status_code == 200:
            # Verifica si el archivo ya existe y ciérralo si está abierto
            if os.path.exists(path):
                os.remove(path)

            with open(path, 'w') as file:
                json.dump(data, file)

            print("Los datos para", i, "se han guardado exitosamente en", path)
        else:
            print("Error al obtener los datos para", i, ". Código de estado:", response.status_code)

Los datos para MSFT se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\MSFT_SMA.json
Los datos para MSFT se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\MSFT_EMA.json
Los datos para GOOG se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\GOOG_SMA.json
Los datos para GOOG se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\GOOG_EMA.json
Los datos para AMZN se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\AMZN_SMA.json
Los datos para AMZN se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\AMZN_EMA.json
Los datos para AAPL se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\AAPL_SMA.json
Los datos para AAPL se han guardado exitosamente en C:\Users\CARLES\Documents\proyect_inversion\technical_indicators\AAPL_EMA.json

In [84]:
with open(r'c:\Users\CARLES\Documents\proyect_inversion\symbols\MSFT.json', 'r') as archivo:
    # Carga los datos del archivo JSON
    data_m = json.load(archivo)
data_m

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'MSFT',
  '3. Last Refreshed': '2024-05-03',
  '4. Output Size': 'Full size',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2024-05-03': {'1. open': '402.2800',
   '2. high': '407.1500',
   '3. low': '401.8600',
   '4. close': '406.6600',
   '5. volume': '17446724'},
  '2024-05-02': {'1. open': '397.6600',
   '2. high': '399.9300',
   '3. low': '394.6515',
   '4. close': '397.8400',
   '5. volume': '17709364'},
  '2024-05-01': {'1. open': '392.6100',
   '2. high': '401.7199',
   '3. low': '390.3100',
   '4. close': '394.9400',
   '5. volume': '23562481'},
  '2024-04-30': {'1. open': '401.4900',
   '2. high': '402.1600',
   '3. low': '389.1700',
   '4. close': '389.3300',
   '5. volume': '28781374'},
  '2024-04-29': {'1. open': '405.2500',
   '2. high': '406.3200',
   '3. low': '399.1900',
   '4. close': '402.2500',
   '5. volume': '19582091'},
  '2024-04-26': {'1. open': '412.1700',
   '2. high': '413.0000',
   '3. low': '405.7601',
   '4. close': '406.3200',
   '5. volume': '29694654'},
  '2024-04-25': {'1. open': '394.0300',
   '2. high': '399.8899',
   '3. low': '388.0300',
   '4. close': '399.0400',
   '5. volume': '40586450'},
  '2024-04-24': {'1. open': '409.5600',
   '2. high': '412.4700',
   '3. low': '406.7800',
   '4. close': '409.0600',
   '5. volume': '15065330'},
  '2024-04-23': {'1. open': '404.2350',
   '2. high': '408.2000',
   '3. low': '403.0600',
   '4. close': '407.5700',
   '5. volume': '15734501'},
  '2024-04-22': {'1. open': '400.0800',
   '2. high': '402.8500',
   '3. low': '395.7500',
   '4. close': '400.9600',
   '5. volume': '20286875'},
  '2024-04-19': {'1. open': '404.0300',
   '2. high': '405.4800',
   '3. low': '397.7700',
   '4. close': '399.1200',
   '5. volume': '30565789'},
  '2024-04-18': {'1. open': '410.6300',
   '2. high': '411.8900',
   '3. low': '403.9500',
   '4. close': '404.2700',
   '5. volume': '21029917'},
  '2024-04-17': {'1. open': '417.2500',
   '2. high': '418.8800',
   '3. low': '410.3300',
   '4. close': '411.8400',
   '5. volume': '15855485'},
  '2024-04-16': {'1. open': '414.5700',
   '2. high': '418.4000',
   '3. low': '413.7301',
   '4. close': '414.5800',
   '5. volume': '16765616'},
  '2024-04-15': {'1. open': '426.6000',
   '2. high': '426.8200',
   '3. low': '413.4300',
   '4. close': '413.6400',
   '5. volume': '20273538'},
  '2024-04-12': {'1. open': '424.0500',
   '2. high': '425.1794',
   '3. low': '419.7700',
   '4. close': '421.9000',
   '5. volume': '19253750'},
  '2024-04-11': {'1. open': '425.8200',
   '2. high': '429.3700',
   '3. low': '422.3600',
   '4. close': '427.9300',
   '5. volume': '17966423'},
  '2024-04-10': {'1. open': '422.1900',
   '2. high': '424.0300',
   '3. low': '419.7000',
   '4. close': '423.2600',
   '5. volume': '16216581'},
  '2024-04-09': {'1. open': '426.4400',
   '2. high': '427.7400',
   '3. low': '421.6200',
   '4. close': '426.2800',
   '5. volume': '12468710'},
  '2024-04-08': {'1. open': '425.1700',
   '2. high': '427.2800',
   '3. low': '423.3000',
   '4. close': '424.5900',
   '5. volume': '14248192'},
  '2024-04-05': {'1. open': '420.0100',
   '2. high': '426.5100',
   '3. low': '418.3200',
   '4. close': '425.5200',
   '5. volume': '16526878'},
  '2024-04-04': {'1. open': '424.9900',
   '2. high': '428.6700',
   '3. low': '417.5700',
   '4. close': '417.8800',
   '5. volume': '19290884'},
  '2024-04-03': {'1. open': '419.7300',
   '2. high': '423.2600',
   '3. low': '419.0850',
   '4. close': '420.4500',
   '5. volume': '16462007'},
  '2024-04-02': {'1. open': '420.1100',
   '2. high': '422.3800',
   '3. low': '417.8400',
   '4. close': '421.4400',
   '5. volume': '17861855'},
  '2024-04-01': {'1. open': '423.9500',
   '2. high': '427.8900',
   '3. low': '422.2200',
   '4. close': '424.5700',
   '5. volume': '15602611'},
  '2024-03-28': {'1. open': '420.9600',
   '2. high': '421.8700',
   '3. low': '419.1200',
   '4. close': '420.7200',
   '5. volume': '21871161'},
  '2024-03-27': {'1. open': '424.4400',
   '2. high': '424.4500',
   '3. low': '419.0100',
   '4. close': '421.4300',
   '5. volume': '16704978'},
  '2024-03-26': {'1. open': '425.6100',
   '2. high': '425.9900',
   '3. low': '421.3500',
   '4. close': '421.6500',
   '5. volume': '16725647'},
  '2024-03-25': {'1. open': '425.2400',
   '2. high': '427.4100',
   '3. low': '421.6100',
   '4. close': '422.8600',
   '5. volume': '18060450'},
  '2024-03-22': {'1. open': '429.7000',
   '2. high': '429.8600',
   '3. low': '426.0700',
   '4. close': '428.7400',
   '5. volume': '17648473'},
  '2024-03-21': {'1. open': '429.8300',
   '2. high': '430.8200',
   '3. low': '427.1600',
   '4. close': '429.3700',
   '5. volume': '21296222'},
  '2024-03-20': {'1. open': '422.0000',
   '2. high': '425.9600',
   '3. low': '420.6600',
   '4. close': '425.2300',
   '5. volume': '17860085'},
  '2024-03-19': {'1. open': '417.8300',
   '2. high': '421.6656',
   '3. low': '415.5500',
   '4. close': '421.4100',
   '5. volume': '19837915'},
  '2024-03-18': {'1. open': '414.2500',
   '2. high': '420.7300',
   '3. low': '413.7800',
   '4. close': '417.3200',
   '5. volume': '20105977'},
  '2024-03-15': {'1. open': '419.2900',
   '2. high': '422.6000',
   '3. low': '412.7900',
   '4. close': '416.4200',
   '5. volume': '45079903'},
  '2024-03-14': {'1. open': '420.2400',
   '2. high': '427.8200',
   '3. low': '417.9900',
   '4. close': '425.2200',
   '5. volume': '33955263'},
  '2024-03-13': {'1. open': '418.1000',
   '2. high': '418.1800',
   '3. low': '411.4500',
   '4. close': '415.1000',
   '5. volume': '16990048'},
  '2024-03-12': {'1. open': '407.6200',
   '2. high': '415.5700',
   '3. low': '406.7900',
   '4. close': '415.2800',
   '5. volume': '21563656'},
  '2024-03-11': {'1. open': '403.7600',
   '2. high': '405.6800',
   '3. low': '401.2600',
   '4. close': '404.5200',
   '5. volume': '15998511'},
  '2024-03-08': {'1. open': '407.9600',
   '2. high': '410.4200',
   '3. low': '404.3300',
   '4. close': '406.2200',
   '5. volume': '18002186'},
  '2024-03-07': {'1. open': '406.1200',
   '2. high': '409.7800',
   '3. low': '402.2400',
   '4. close': '409.1400',
   '5. volume': '18718479'},
  '2024-03-06': {'1. open': '402.9700',
   '2. high': '405.1600',
   '3. low': '398.3900',
   '4. close': '402.0900',
   '5. volume': '22344149'},
  '2024-03-05': {'1. open': '413.9600',
   '2. high': '414.2500',
   '3. low': '400.6400',
   '4. close': '402.6500',
   '5. volume': '26919177'},
  '2024-03-04': {'1. open': '413.4400',
   '2. high': '417.3500',
   '3. low': '412.3200',
   '4. close': '414.9200',
   '5. volume': '17595956'},
  '2024-03-01': {'1. open': '411.2700',
   '2. high': '415.8700',
   '3. low': '410.8800',
   '4. close': '415.5000',
   '5. volume': '17823445'},
  '2024-02-29': {'1. open': '408.6400',
   '2. high': '414.2000',
   '3. low': '405.9200',
   '4. close': '413.6400',
   '5. volume': '31947263'},
  '2024-02-28': {'1. open': '408.1750',
   '2. high': '409.3000',
   '3. low': '405.3201',
   '4. close': '407.7200',
   '5. volume': '13183125'},
  '2024-02-27': {'1. open': '407.9900',
   '2. high': '408.3200',
   '3. low': '403.8500',
   '4. close': '407.4800',
   '5. volume': '14835827'},
  '2024-02-26': {'1. open': '411.4550',
   '2. high': '412.1600',
   '3. low': '407.3600',
   '4. close': '407.5400',
   '5. volume': '16193505'},
  '2024-02-23': {'1. open': '415.6700',
   '2. high': '415.8600',
   '3. low': '408.9700',
   '4. close': '410.3400',
   '5. volume': '16295879'},
  '2024-02-22': {'1. open': '410.1900',
   '2. high': '412.8300',
   '3. low': '408.5700',
   '4. close': '411.6500',
   '5. volume': '27009869'},
  '2024-02-21': {'1. open': '400.1700',
   '2. high': '402.2900',
   '3. low': '397.2200',
   '4. close': '402.1800',
   '5. volume': '18631072'},
  '2024-02-20': {'1. open': '403.2400',
   '2. high': '404.4900',
   '3. low': '398.0100',
   '4. close': '402.7900',
   '5. volume': '24307915'},
  '2024-02-16': {'1. open': '407.9600',
   '2. high': '408.2900',
   '3. low': '403.4400',
   '4. close': '404.0600',
   '5. volume': '22296495'},
  '2024-02-15': {'1. open': '408.1400',
   '2. high': '409.1300',
   '3. low': '404.2900',
   '4. close': '406.5600',
   '5. volume': '21825525'},
  '2024-02-14': {'1. open': '408.0700',
   '2. high': '409.8400',
   '3. low': '404.5700',
   '4. close': '409.4900',
   '5. volume': '20401190'},
  '2024-02-13': {'1. open': '404.9400',
   '2. high': '410.0710',
   '3. low': '403.3900',
   '4. close': '406.3200',
   '5. volume': '27824936'},
  '2024-02-12': {'1. open': '420.5550',
   '2. high': '420.7400',
   '3. low': '414.7500',
   '4. close': '415.2600',
   '5. volume': '21202921'},
  '2024-02-09': {'1. open': '415.2500',
   '2. high': '420.8200',
   '3. low': '415.0900',
   '4. close': '420.5500',
   '5. volume': '22032844'},
  '2024-02-08': {'1. open': '414.0500',
   '2. high': '415.5600',
   '3. low': '412.5300',
   '4. close': '414.1100',
   '5. volume': '21225257'},
  '2024-02-07': {'1. open': '407.4400',
   '2. high': '414.3000',
   '3. low': '407.4000',
   '4. close': '414.0500',
   '5. volume': '22340526'},
  '2024-02-06': {'1. open': '405.8800',
   '2. high': '407.9700',
   '3. low': '402.9100',
   '4. close': '405.4900',
   '5. volume': '18382624'},
  '2024-02-05': {'1. open': '409.9000',
   '2. high': '411.1600',
   '3. low': '403.9900',
   '4. close': '405.6500',
   '5. volume': '25352286'},
  '2024-02-02': {'1. open': '403.8100',
   '2. high': '412.6500',
   '3. low': '403.5600',
   '4. close': '411.2200',
   '5. volume': '28256670'},
  '2024-02-01': {'1. open': '401.8300',
   '2. high': '408.0000',
   '3. low': '401.8000',
   '4. close': '403.7800',
   '5. volume': '30657726'},
  '2024-01-31': {'1. open': '406.9600',
   '2. high': '415.3200',
   '3. low': '397.2100',
   '4. close': '397.5800',
   '5. volume': '47871097'},
  '2024-01-30': {'1. open': '412.2600',
   '2. high': '413.0500',
   '3. low': '406.4501',
   '4. close': '408.5900',
   '5. volume': '33477610'},
  '2024-01-29': {'1. open': '406.0600',
   '2. high': '409.9800',
   '3. low': '404.3300',
   '4. close': '409.7200',
   '5. volume': '24510236'},
  '2024-01-26': {'1. open': '404.3700',
   '2. high': '406.1700',
   '3. low': '402.4300',
   '4. close': '403.9300',
   '5. volume': '17803271'},
  '2024-01-25': {'1. open': '404.3200',
   '2. high': '407.0100',
   '3. low': '402.5294',
   '4. close': '404.8700',
   '5. volume': '21021155'},
  '2024-01-24': {'1. open': '401.5400',
   '2. high': '405.6300',
   '3. low': '400.4500',
   '4. close': '402.5600',
   '5. volume': '23281889'},
  '2024-01-23': {'1. open': '395.7500',
   '2. high': '399.3800',
   '3. low': '393.9300',
   '4. close': '398.9000',
   '5. volume': '20525882'},
  '2024-01-22': {'1. open': '400.0200',
   '2. high': '400.6200',
   '3. low': '393.5900',
   '4. close': '396.5100',
   '5. volume': '27016902'},
  '2024-01-19': {'1. open': '395.7600',
   '2. high': '398.6700',
   '3. low': '393.5000',
   '4. close': '398.6700',
   '5. volume': '29331136'},
  '2024-01-18': {'1. open': '391.7200',
   '2. high': '393.9900',
   '3. low': '390.1200',
   '4. close': '393.8700',
   '5. volume': '23392068'},
  '2024-01-17': {'1. open': '387.9800',
   '2. high': '390.1100',
   '3. low': '384.8100',
   '4. close': '389.4700',
   '5. volume': '22234108'},
  '2024-01-16': {'1. open': '393.6600',
   '2. high': '394.0300',
   '3. low': '387.6229',
   '4. close': '390.2700',
   '5. volume': '27202268'},
  '2024-01-12': {'1. open': '385.4900',
   '2. high': '388.6800',
   '3. low': '384.6500',
   '4. close': '388.4700',
   '5. volume': '21661153'},
  '2024-01-11': {'1. open': '386.0000',
   '2. high': '390.6800',
   '3. low': '380.3800',
   '4. close': '384.6300',
   '5. volume': '27850846'},
  '2024-01-10': {'1. open': '376.3700',
   '2. high': '384.1700',
   '3. low': '376.3200',
   '4. close': '382.7700',
   '5. volume': '25514245'},
  '2024-01-09': {'1. open': '372.0100',
   '2. high': '375.9900',
   '3. low': '371.1900',
   '4. close': '375.7900',
   '5. volume': '20829953'},
  '2024-01-08': {'1. open': '369.3000',
   '2. high': '375.2000',
   '3. low': '369.0100',
   '4. close': '374.6900',
   '5. volume': '23133967'},
  '2024-01-05': {'1. open': '368.9700',
   '2. high': '372.0600',
   '3. low': '366.5000',
   '4. close': '367.7500',
   '5. volume': '20074451'},
  '2024-01-04': {'1. open': '370.6650',
   '2. high': '373.1000',
   '3. low': '367.1700',
   '4. close': '367.9400',
   '5. volume': '20901502'},
  '2024-01-03': {'1. open': '369.0100',
   '2. high': '373.2562',
   '3. low': '368.5100',
   '4. close': '370.6000',
   '5. volume': '23083465'},
  '2024-01-02': {'1. open': '373.8600',
   '2. high': '375.9000',
   '3. low': '366.7710',
   '4. close': '370.8700',
   '5. volume': '25258633'},
  '2023-12-29': {'1. open': '376.0000',
   '2. high': '377.1600',
   '3. low': '373.4800',
   '4. close': '376.0400',
   '5. volume': '18730838'},
  '2023-12-28': {'1. open': '375.3700',
   '2. high': '376.4580',
   '3. low': '374.1600',
   '4. close': '375.2800',
   '5. volume': '14327013'},
  '2023-12-27': {'1. open': '373.6900',
   '2. high': '375.0600',
   '3. low': '372.8116',
   '4. close': '374.0700',
   '5. volume': '14872756'},
  '2023-12-26': {'1. open': '375.0000',
   '2. high': '376.9400',
   '3. low': '373.5000',
   '4. close': '374.6600',
   '5. volume': '12673050'},
  '2023-12-22': {'1. open': '373.6800',
   '2. high': '375.1800',
   '3. low': '372.7100',
   '4. close': '374.5800',
   '5. volume': '17107484'},
  '2023-12-21': {'1. open': '372.5600',
   '2. high': '374.4100',
   '3. low': '370.0400',
   '4. close': '373.5400',
   '5. volume': '17708006'},
  '2023-12-20': {'1. open': '375.0000',
   '2. high': '376.0300',
   '3. low': '370.5300',
   '4. close': '370.6200',
   '5. volume': '26316650'},
  '2023-12-19': {'1. open': '371.4900',
   '2. high': '373.2600',
   '3. low': '369.8400',
   '4. close': '373.2600',
   '5. volume': '20533284'},
  '2023-12-18': {'1. open': '369.4500',
   '2. high': '373.0000',
   '3. low': '368.6800',
   '4. close': '372.6500',
   '5. volume': '21802878'},
  '2023-12-15': {'1. open': '366.8500',
   '2. high': '372.4000',
   '3. low': '366.2800',
   '4. close': '370.7300',
   '5. volume': '78502324'},
  '2023-12-14': {'1. open': '373.3100',
   '2. high': '373.7600',
   '3. low': '364.1300',
   '4. close': '365.9300',
   '5. volume': '43277461'},
  '2023-12-13': {'1. open': '376.0200',
   '2. high': '377.6361',
   '3. low': '370.7700',
   '4. close': '374.3700',
   '5. volume': '30955531'},
  '2023-12-12': {'1. open': '370.8500',
   '2. high': '374.4200',
   '3. low': '370.4600',
   '4. close': '374.3800',
   '5. volume': '24838253'},
  '2023-12-11': {'1. open': '368.4800',
   '2. high': '371.6000',
   '3. low': '366.1000',
   '4. close': '371.3000',
   '5. volume': '27708757'},
  '2023-12-08': {'1. open': '369.2000',
   '2. high': '374.4600',
   '3. low': '368.2300',
   '4. close': '374.2300',
   '5. volume': '20154366'},
  '2023-12-07': {'1. open': '368.2300',
   '2. high': '371.4527',
   '3. low': '366.3200',
   '4. close': '370.9500',
   '5. volume': '23118864'},
  '2023-12-06': {'1. open': '373.5400',
   '2. high': '374.1800',
   '3. low': '368.0300',
   '4. close': '368.8000',
   '5. volume': '21118348'},
  '2023-12-05': {'1. open': '366.4500',
   '2. high': '373.0750',
   '3. low': '365.6210',
   '4. close': '372.5200',
   '5. volume': '23065035'},
  '2023-12-04': {'1. open': '369.1000',
   '2. high': '369.5200',
   '3. low': '362.9000',
   '4. close': '369.1400',
   '5. volume': '32063305'},
  '2023-12-01': {'1. open': '376.7600',
   '2. high': '378.1600',
   '3. low': '371.3100',
   '4. close': '374.5100',
   '5. volume': '33040472'},
  '2023-11-30': {'1. open': '378.4900',
   '2. high': '380.0900',
   '3. low': '375.4700',
   '4. close': '378.9100',
   '5. volume': '30554415'},
  '2023-11-29': {'1. open': '383.7600',
   '2. high': '384.3000',
   '3. low': '377.4400',
   '4. close': '378.8500',
   '5. volume': '28963399'},
  '2023-11-28': {'1. open': '378.3500',
   '2. high': '383.0000',
   '3. low': '378.1600',
   '4. close': '382.7000',
   '5. volume': '20453112'},
  '2023-11-27': {'1. open': '376.7800',
   '2. high': '380.6400',
   '3. low': '376.2000',
   '4. close': '378.6100',
   '5. volume': '22179228'},
  '2023-11-24': {'1. open': '377.3300',
   '2. high': '377.9700',
   '3. low': '375.1350',
   '4. close': '377.4300',
   '5. volume': '10176649'},
  '2023-11-22': {'1. open': '378.0000',
   '2. high': '379.7899',
   '3. low': '374.9650',
   '4. close': '377.8500',
   '5. volume': '23361184'},
  '2023-11-21': {'1. open': '375.6700',
   '2. high': '376.2215',
   '3. low': '371.1200',
   '4. close': '373.0700',
   '5. volume': '28423145'},
  '2023-11-20': {'1. open': '371.2200',
   '2. high': '378.8700',
   '3. low': '371.0000',
   '4. close': '377.4400',
   '5. volume': '52528964'},
  '2023-11-17': {'1. open': '373.6100',
   '2. high': '374.3700',
   '3. low': '367.0000',
   '4. close': '369.8500',
   '5. volume': '40325371'},
  '2023-11-16': {'1. open': '370.9600',
   '2. high': '376.3500',
   '3. low': '370.1800',
   '4. close': '376.1700',
   '5. volume': '27182315'},
  '2023-11-15': {'1. open': '371.2800',
   '2. high': '373.1300',
   '3. low': '367.1100',
   '4. close': '369.6700',
   '5. volume': '26860095'},
  '2023-11-14': {'1. open': '371.0100',
   '2. high': '371.9500',
   '3. low': '367.3454',
   '4. close': '370.2700',
   '5. volume': '27683862'},
  '2023-11-13': {'1. open': '368.2200',
   '2. high': '368.4700',
   '3. low': '365.9000',
   '4. close': '366.6800',
   '5. volume': '19986506'},
  '2023-11-10': {'1. open': '361.4900',
   '2. high': '370.1000',
   '3. low': '361.0700',
   '4. close': '369.6700',
   '5. volume': '28065164'},
  '2023-11-09': {'1. open': '362.3000',
   '2. high': '364.7900',
   '3. low': '360.3620',
   '4. close': '360.6900',
   '5. volume': '24847331'},
  '2023-11-08': {'1. open': '361.6800',
   '2. high': '363.8700',
   '3. low': '360.5500',
   '4. close': '363.2000',
   '5. volume': '26767828'},
  '2023-11-07': {'1. open': '359.4000',
   '2. high': '362.4600',
   '3. low': '357.6300',
   '4. close': '360.5300',
   '5. volume': '25833931'},
  '2023-11-06': {'1. open': '353.4500',
   '2. high': '357.5400',
   '3. low': '353.3500',
   '4. close': '356.5300',
   '5. volume': '23828301'},
  '2023-11-03': {'1. open': '349.6300',
   '2. high': '354.3900',
   '3. low': '347.3300',
   '4. close': '352.8000',
   '5. volume': '23637673'},
  '2023-11-02': {'1. open': '347.2400',
   '2. high': '348.8300',
   '3. low': '344.7700',
   '4. close': '348.3200',
   '5. volume': '24348072'},
  '2023-11-01': {'1. open': '339.7900',
   '2. high': '347.4200',
   '3. low': '339.6500',
   '4. close': '346.0700',
   '5. volume': '28158819'},
  '2023-10-31': {'1. open': '338.8500',
   '2. high': '339.0000',
   '3. low': '334.6900',
   '4. close': '338.1100',
   '5. volume': '20265282'},
  '2023-10-30': {'1. open': '333.4100',
   '2. high': '339.4500',
   '3. low': '331.8300',
   '4. close': '337.3100',
   '5. volume': '22828082'},
  '2023-10-27': {'1. open': '330.4250',
   '2. high': '336.7200',
   '3. low': '328.4007',
   '4. close': '329.8100',
   '5. volume': '29856522'},
  '2023-10-26': {'1. open': '340.5400',
   '2. high': '341.6300',
   '3. low': '326.9400',
   '4. close': '327.8900',
   '5. volume': '37828543'},
  '2023-10-25': {'1. open': '345.0200',
   '2. high': '346.2000',
   '3. low': '337.6200',
   '4. close': '340.6700',
   '5. volume': '55053828'},
  '2023-10-24': {'1. open': '331.3000',
   '2. high': '331.8400',
   '3. low': '327.6000',
   '4. close': '330.5300',
   '5. volume': '31153571'},
  '2023-10-23': {'1. open': '325.4700',
   '2. high': '332.7250',
   '3. low': '324.3900',
   '4. close': '329.3200',
   '5. volume': '24374748'},
  '2023-10-20': {'1. open': '331.7200',
   '2. high': '331.9200',

In [123]:
data_m

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'MSFT',
  '3. Last Refreshed': '2024-05-03',
  '4. Output Size': 'Full size',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2024-05-03': {'1. open': '402.2800',
   '2. high': '407.1500',
   '3. low': '401.8600',
   '4. close': '406.6600',
   '5. volume': '17446724'},
  '2024-05-02': {'1. open': '397.6600',
   '2. high': '399.9300',
   '3. low': '394.6515',
   '4. close': '397.8400',
   '5. volume': '17709364'},
  '2024-05-01': {'1. open': '392.6100',
   '2. high': '401.7199',
   '3. low': '390.3100',
   '4. close': '394.9400',
   '5. volume': '23562481'},
  '2024-04-30': {'1. open': '401.4900',
   '2. high': '402.1600',
   '3. low': '389.1700',
   '4. close': '389.3300',
   '5. volume': '28781374'},
  '2024-04-29': {'1. open': '405.2500',
   '2. high': '406.3200',
   '3. low': '399.1900',
   '4. close': '402.2500',
   '5. volume': '19582091'},
  '2024-04-26': {'1. open': '412.1700',
   '2. high': '413.0000',
   '3. low': '405.7601',
   '4. close': '406.3200',
   '5. volume': '29694654'},
  '2024-04-25': {'1. open': '394.0300',
   '2. high': '399.8899',
   '3. low': '388.0300',
   '4. close': '399.0400',
   '5. volume': '40586450'},
  '2024-04-24': {'1. open': '409.5600',
   '2. high': '412.4700',
   '3. low': '406.7800',
   '4. close': '409.0600',
   '5. volume': '15065330'},
  '2024-04-23': {'1. open': '404.2350',
   '2. high': '408.2000',
   '3. low': '403.0600',
   '4. close': '407.5700',
   '5. volume': '15734501'},
  '2024-04-22': {'1. open': '400.0800',
   '2. high': '402.8500',
   '3. low': '395.7500',
   '4. close': '400.9600',
   '5. volume': '20286875'},
  '2024-04-19': {'1. open': '404.0300',
   '2. high': '405.4800',
   '3. low': '397.7700',
   '4. close': '399.1200',
   '5. volume': '30565789'},
  '2024-04-18': {'1. open': '410.6300',
   '2. high': '411.8900',
   '3. low': '403.9500',
   '4. close': '404.2700',
   '5. volume': '21029917'},
  '2024-04-17': {'1. open': '417.2500',
   '2. high': '418.8800',
   '3. low': '410.3300',
   '4. close': '411.8400',
   '5. volume': '15855485'},
  '2024-04-16': {'1. open': '414.5700',
   '2. high': '418.4000',
   '3. low': '413.7301',
   '4. close': '414.5800',
   '5. volume': '16765616'},
  '2024-04-15': {'1. open': '426.6000',
   '2. high': '426.8200',
   '3. low': '413.4300',
   '4. close': '413.6400',
   '5. volume': '20273538'},
  '2024-04-12': {'1. open': '424.0500',
   '2. high': '425.1794',
   '3. low': '419.7700',
   '4. close': '421.9000',
   '5. volume': '19253750'},
  '2024-04-11': {'1. open': '425.8200',
   '2. high': '429.3700',
   '3. low': '422.3600',
   '4. close': '427.9300',
   '5. volume': '17966423'},
  '2024-04-10': {'1. open': '422.1900',
   '2. high': '424.0300',
   '3. low': '419.7000',
   '4. close': '423.2600',
   '5. volume': '16216581'},
  '2024-04-09': {'1. open': '426.4400',
   '2. high': '427.7400',
   '3. low': '421.6200',
   '4. close': '426.2800',
   '5. volume': '12468710'},
  '2024-04-08': {'1. open': '425.1700',
   '2. high': '427.2800',
   '3. low': '423.3000',
   '4. close': '424.5900',
   '5. volume': '14248192'},
  '2024-04-05': {'1. open': '420.0100',
   '2. high': '426.5100',
   '3. low': '418.3200',
   '4. close': '425.5200',
   '5. volume': '16526878'},
  '2024-04-04': {'1. open': '424.9900',
   '2. high': '428.6700',
   '3. low': '417.5700',
   '4. close': '417.8800',
   '5. volume': '19290884'},
  '2024-04-03': {'1. open': '419.7300',
   '2. high': '423.2600',
   '3. low': '419.0850',
   '4. close': '420.4500',
   '5. volume': '16462007'},
  '2024-04-02': {'1. open': '420.1100',
   '2. high': '422.3800',
   '3. low': '417.8400',
   '4. close': '421.4400',
   '5. volume': '17861855'},
  '2024-04-01': {'1. open': '423.9500',
   '2. high': '427.8900',
   '3. low': '422.2200',
   '4. close': '424.5700',
   '5. volume': '15602611'},
  '2024-03-28': {'1. open': '420.9600',
   '2. high': '421.8700',
   '3. low': '419.1200',
   '4. close': '420.7200',
   '5. volume': '21871161'},
  '2024-03-27': {'1. open': '424.4400',
   '2. high': '424.4500',
   '3. low': '419.0100',
   '4. close': '421.4300',
   '5. volume': '16704978'},
  '2024-03-26': {'1. open': '425.6100',
   '2. high': '425.9900',
   '3. low': '421.3500',
   '4. close': '421.6500',
   '5. volume': '16725647'},
  '2024-03-25': {'1. open': '425.2400',
   '2. high': '427.4100',
   '3. low': '421.6100',
   '4. close': '422.8600',
   '5. volume': '18060450'},
  '2024-03-22': {'1. open': '429.7000',
   '2. high': '429.8600',
   '3. low': '426.0700',
   '4. close': '428.7400',
   '5. volume': '17648473'},
  '2024-03-21': {'1. open': '429.8300',
   '2. high': '430.8200',
   '3. low': '427.1600',
   '4. close': '429.3700',
   '5. volume': '21296222'},
  '2024-03-20': {'1. open': '422.0000',
   '2. high': '425.9600',
   '3. low': '420.6600',
   '4. close': '425.2300',
   '5. volume': '17860085'},
  '2024-03-19': {'1. open': '417.8300',
   '2. high': '421.6656',
   '3. low': '415.5500',
   '4. close': '421.4100',
   '5. volume': '19837915'},
  '2024-03-18': {'1. open': '414.2500',
   '2. high': '420.7300',
   '3. low': '413.7800',
   '4. close': '417.3200',
   '5. volume': '20105977'},
  '2024-03-15': {'1. open': '419.2900',
   '2. high': '422.6000',
   '3. low': '412.7900',
   '4. close': '416.4200',
   '5. volume': '45079903'},
  '2024-03-14': {'1. open': '420.2400',
   '2. high': '427.8200',
   '3. low': '417.9900',
   '4. close': '425.2200',
   '5. volume': '33955263'},
  '2024-03-13': {'1. open': '418.1000',
   '2. high': '418.1800',
   '3. low': '411.4500',
   '4. close': '415.1000',
   '5. volume': '16990048'},
  '2024-03-12': {'1. open': '407.6200',
   '2. high': '415.5700',
   '3. low': '406.7900',
   '4. close': '415.2800',
   '5. volume': '21563656'},
  '2024-03-11': {'1. open': '403.7600',
   '2. high': '405.6800',
   '3. low': '401.2600',
   '4. close': '404.5200',
   '5. volume': '15998511'},
  '2024-03-08': {'1. open': '407.9600',
   '2. high': '410.4200',
   '3. low': '404.3300',
   '4. close': '406.2200',
   '5. volume': '18002186'},
  '2024-03-07': {'1. open': '406.1200',
   '2. high': '409.7800',
   '3. low': '402.2400',
   '4. close': '409.1400',
   '5. volume': '18718479'},
  '2024-03-06': {'1. open': '402.9700',
   '2. high': '405.1600',
   '3. low': '398.3900',
   '4. close': '402.0900',
   '5. volume': '22344149'},
  '2024-03-05': {'1. open': '413.9600',
   '2. high': '414.2500',
   '3. low': '400.6400',
   '4. close': '402.6500',
   '5. volume': '26919177'},
  '2024-03-04': {'1. open': '413.4400',
   '2. high': '417.3500',
   '3. low': '412.3200',
   '4. close': '414.9200',
   '5. volume': '17595956'},
  '2024-03-01': {'1. open': '411.2700',
   '2. high': '415.8700',
   '3. low': '410.8800',
   '4. close': '415.5000',
   '5. volume': '17823445'},
  '2024-02-29': {'1. open': '408.6400',
   '2. high': '414.2000',
   '3. low': '405.9200',
   '4. close': '413.6400',
   '5. volume': '31947263'},
  '2024-02-28': {'1. open': '408.1750',
   '2. high': '409.3000',
   '3. low': '405.3201',
   '4. close': '407.7200',
   '5. volume': '13183125'},
  '2024-02-27': {'1. open': '407.9900',
   '2. high': '408.3200',
   '3. low': '403.8500',
   '4. close': '407.4800',
   '5. volume': '14835827'},
  '2024-02-26': {'1. open': '411.4550',
   '2. high': '412.1600',
   '3. low': '407.3600',
   '4. close': '407.5400',
   '5. volume': '16193505'},
  '2024-02-23': {'1. open': '415.6700',
   '2. high': '415.8600',
   '3. low': '408.9700',
   '4. close': '410.3400',
   '5. volume': '16295879'},
  '2024-02-22': {'1. open': '410.1900',
   '2. high': '412.8300',
   '3. low': '408.5700',
   '4. close': '411.6500',
   '5. volume': '27009869'},
  '2024-02-21': {'1. open': '400.1700',
   '2. high': '402.2900',
   '3. low': '397.2200',
   '4. close': '402.1800',
   '5. volume': '18631072'},
  '2024-02-20': {'1. open': '403.2400',
   '2. high': '404.4900',
   '3. low': '398.0100',
   '4. close': '402.7900',
   '5. volume': '24307915'},
  '2024-02-16': {'1. open': '407.9600',
   '2. high': '408.2900',
   '3. low': '403.4400',
   '4. close': '404.0600',
   '5. volume': '22296495'},
  '2024-02-15': {'1. open': '408.1400',
   '2. high': '409.1300',
   '3. low': '404.2900',
   '4. close': '406.5600',
   '5. volume': '21825525'},
  '2024-02-14': {'1. open': '408.0700',
   '2. high': '409.8400',
   '3. low': '404.5700',
   '4. close': '409.4900',
   '5. volume': '20401190'},
  '2024-02-13': {'1. open': '404.9400',
   '2. high': '410.0710',
   '3. low': '403.3900',
   '4. close': '406.3200',
   '5. volume': '27824936'},
  '2024-02-12': {'1. open': '420.5550',
   '2. high': '420.7400',
   '3. low': '414.7500',
   '4. close': '415.2600',
   '5. volume': '21202921'},
  '2024-02-09': {'1. open': '415.2500',
   '2. high': '420.8200',
   '3. low': '415.0900',
   '4. close': '420.5500',
   '5. volume': '22032844'},
  '2024-02-08': {'1. open': '414.0500',
   '2. high': '415.5600',
   '3. low': '412.5300',
   '4. close': '414.1100',
   '5. volume': '21225257'},
  '2024-02-07': {'1. open': '407.4400',
   '2. high': '414.3000',
   '3. low': '407.4000',
   '4. close': '414.0500',
   '5. volume': '22340526'},
  '2024-02-06': {'1. open': '405.8800',
   '2. high': '407.9700',
   '3. low': '402.9100',
   '4. close': '405.4900',
   '5. volume': '18382624'},
  '2024-02-05': {'1. open': '409.9000',
   '2. high': '411.1600',
   '3. low': '403.9900',
   '4. close': '405.6500',
   '5. volume': '25352286'},
  '2024-02-02': {'1. open': '403.8100',
   '2. high': '412.6500',
   '3. low': '403.5600',
   '4. close': '411.2200',
   '5. volume': '28256670'},
  '2024-02-01': {'1. open': '401.8300',
   '2. high': '408.0000',
   '3. low': '401.8000',
   '4. close': '403.7800',
   '5. volume': '30657726'},
  '2024-01-31': {'1. open': '406.9600',
   '2. high': '415.3200',
   '3. low': '397.2100',
   '4. close': '397.5800',
   '5. volume': '47871097'},
  '2024-01-30': {'1. open': '412.2600',
   '2. high': '413.0500',
   '3. low': '406.4501',
   '4. close': '408.5900',
   '5. volume': '33477610'},
  '2024-01-29': {'1. open': '406.0600',
   '2. high': '409.9800',
   '3. low': '404.3300',
   '4. close': '409.7200',
   '5. volume': '24510236'},
  '2024-01-26': {'1. open': '404.3700',
   '2. high': '406.1700',
   '3. low': '402.4300',
   '4. close': '403.9300',
   '5. volume': '17803271'},
  '2024-01-25': {'1. open': '404.3200',
   '2. high': '407.0100',
   '3. low': '402.5294',
   '4. close': '404.8700',
   '5. volume': '21021155'},
  '2024-01-24': {'1. open': '401.5400',
   '2. high': '405.6300',
   '3. low': '400.4500',
   '4. close': '402.5600',
   '5. volume': '23281889'},
  '2024-01-23': {'1. open': '395.7500',
   '2. high': '399.3800',
   '3. low': '393.9300',
   '4. close': '398.9000',
   '5. volume': '20525882'},
  '2024-01-22': {'1. open': '400.0200',
   '2. high': '400.6200',
   '3. low': '393.5900',
   '4. close': '396.5100',
   '5. volume': '27016902'},
  '2024-01-19': {'1. open': '395.7600',
   '2. high': '398.6700',
   '3. low': '393.5000',
   '4. close': '398.6700',
   '5. volume': '29331136'},
  '2024-01-18': {'1. open': '391.7200',
   '2. high': '393.9900',
   '3. low': '390.1200',
   '4. close': '393.8700',
   '5. volume': '23392068'},
  '2024-01-17': {'1. open': '387.9800',
   '2. high': '390.1100',
   '3. low': '384.8100',
   '4. close': '389.4700',
   '5. volume': '22234108'},
  '2024-01-16': {'1. open': '393.6600',
   '2. high': '394.0300',
   '3. low': '387.6229',
   '4. close': '390.2700',
   '5. volume': '27202268'},
  '2024-01-12': {'1. open': '385.4900',
   '2. high': '388.6800',
   '3. low': '384.6500',
   '4. close': '388.4700',
   '5. volume': '21661153'},
  '2024-01-11': {'1. open': '386.0000',
   '2. high': '390.6800',
   '3. low': '380.3800',
   '4. close': '384.6300',
   '5. volume': '27850846'},
  '2024-01-10': {'1. open': '376.3700',
   '2. high': '384.1700',
   '3. low': '376.3200',
   '4. close': '382.7700',
   '5. volume': '25514245'},
  '2024-01-09': {'1. open': '372.0100',
   '2. high': '375.9900',
   '3. low': '371.1900',
   '4. close': '375.7900',
   '5. volume': '20829953'},
  '2024-01-08': {'1. open': '369.3000',
   '2. high': '375.2000',
   '3. low': '369.0100',
   '4. close': '374.6900',
   '5. volume': '23133967'},
  '2024-01-05': {'1. open': '368.9700',
   '2. high': '372.0600',
   '3. low': '366.5000',
   '4. close': '367.7500',
   '5. volume': '20074451'},
  '2024-01-04': {'1. open': '370.6650',
   '2. high': '373.1000',
   '3. low': '367.1700',
   '4. close': '367.9400',
   '5. volume': '20901502'},
  '2024-01-03': {'1. open': '369.0100',
   '2. high': '373.2562',
   '3. low': '368.5100',
   '4. close': '370.6000',
   '5. volume': '23083465'},
  '2024-01-02': {'1. open': '373.8600',
   '2. high': '375.9000',
   '3. low': '366.7710',
   '4. close': '370.8700',
   '5. volume': '25258633'},
  '2023-12-29': {'1. open': '376.0000',
   '2. high': '377.1600',
   '3. low': '373.4800',
   '4. close': '376.0400',
   '5. volume': '18730838'},
  '2023-12-28': {'1. open': '375.3700',
   '2. high': '376.4580',
   '3. low': '374.1600',
   '4. close': '375.2800',
   '5. volume': '14327013'},
  '2023-12-27': {'1. open': '373.6900',
   '2. high': '375.0600',
   '3. low': '372.8116',
   '4. close': '374.0700',
   '5. volume': '14872756'},
  '2023-12-26': {'1. open': '375.0000',
   '2. high': '376.9400',
   '3. low': '373.5000',
   '4. close': '374.6600',
   '5. volume': '12673050'},
  '2023-12-22': {'1. open': '373.6800',
   '2. high': '375.1800',
   '3. low': '372.7100',
   '4. close': '374.5800',
   '5. volume': '17107484'},
  '2023-12-21': {'1. open': '372.5600',
   '2. high': '374.4100',
   '3. low': '370.0400',
   '4. close': '373.5400',
   '5. volume': '17708006'},
  '2023-12-20': {'1. open': '375.0000',
   '2. high': '376.0300',
   '3. low': '370.5300',
   '4. close': '370.6200',
   '5. volume': '26316650'},
  '2023-12-19': {'1. open': '371.4900',
   '2. high': '373.2600',
   '3. low': '369.8400',
   '4. close': '373.2600',
   '5. volume': '20533284'},
  '2023-12-18': {'1. open': '369.4500',
   '2. high': '373.0000',
   '3. low': '368.6800',
   '4. close': '372.6500',
   '5. volume': '21802878'},
  '2023-12-15': {'1. open': '366.8500',
   '2. high': '372.4000',
   '3. low': '366.2800',
   '4. close': '370.7300',
   '5. volume': '78502324'},
  '2023-12-14': {'1. open': '373.3100',
   '2. high': '373.7600',
   '3. low': '364.1300',
   '4. close': '365.9300',
   '5. volume': '43277461'},
  '2023-12-13': {'1. open': '376.0200',
   '2. high': '377.6361',
   '3. low': '370.7700',
   '4. close': '374.3700',
   '5. volume': '30955531'},
  '2023-12-12': {'1. open': '370.8500',
   '2. high': '374.4200',
   '3. low': '370.4600',
   '4. close': '374.3800',
   '5. volume': '24838253'},
  '2023-12-11': {'1. open': '368.4800',
   '2. high': '371.6000',
   '3. low': '366.1000',
   '4. close': '371.3000',
   '5. volume': '27708757'},
  '2023-12-08': {'1. open': '369.2000',
   '2. high': '374.4600',
   '3. low': '368.2300',
   '4. close': '374.2300',
   '5. volume': '20154366'},
  '2023-12-07': {'1. open': '368.2300',
   '2. high': '371.4527',
   '3. low': '366.3200',
   '4. close': '370.9500',
   '5. volume': '23118864'},
  '2023-12-06': {'1. open': '373.5400',
   '2. high': '374.1800',
   '3. low': '368.0300',
   '4. close': '368.8000',
   '5. volume': '21118348'},
  '2023-12-05': {'1. open': '366.4500',
   '2. high': '373.0750',
   '3. low': '365.6210',
   '4. close': '372.5200',
   '5. volume': '23065035'},
  '2023-12-04': {'1. open': '369.1000',
   '2. high': '369.5200',
   '3. low': '362.9000',
   '4. close': '369.1400',
   '5. volume': '32063305'},
  '2023-12-01': {'1. open': '376.7600',
   '2. high': '378.1600',
   '3. low': '371.3100',
   '4. close': '374.5100',
   '5. volume': '33040472'},
  '2023-11-30': {'1. open': '378.4900',
   '2. high': '380.0900',
   '3. low': '375.4700',
   '4. close': '378.9100',
   '5. volume': '30554415'},
  '2023-11-29': {'1. open': '383.7600',
   '2. high': '384.3000',
   '3. low': '377.4400',
   '4. close': '378.8500',
   '5. volume': '28963399'},
  '2023-11-28': {'1. open': '378.3500',
   '2. high': '383.0000',
   '3. low': '378.1600',
   '4. close': '382.7000',
   '5. volume': '20453112'},
  '2023-11-27': {'1. open': '376.7800',
   '2. high': '380.6400',
   '3. low': '376.2000',
   '4. close': '378.6100',
   '5. volume': '22179228'},
  '2023-11-24': {'1. open': '377.3300',
   '2. high': '377.9700',
   '3. low': '375.1350',
   '4. close': '377.4300',
   '5. volume': '10176649'},
  '2023-11-22': {'1. open': '378.0000',
   '2. high': '379.7899',
   '3. low': '374.9650',
   '4. close': '377.8500',
   '5. volume': '23361184'},
  '2023-11-21': {'1. open': '375.6700',
   '2. high': '376.2215',
   '3. low': '371.1200',
   '4. close': '373.0700',
   '5. volume': '28423145'},
  '2023-11-20': {'1. open': '371.2200',
   '2. high': '378.8700',
   '3. low': '371.0000',
   '4. close': '377.4400',
   '5. volume': '52528964'},
  '2023-11-17': {'1. open': '373.6100',
   '2. high': '374.3700',
   '3. low': '367.0000',
   '4. close': '369.8500',
   '5. volume': '40325371'},
  '2023-11-16': {'1. open': '370.9600',
   '2. high': '376.3500',
   '3. low': '370.1800',
   '4. close': '376.1700',
   '5. volume': '27182315'},
  '2023-11-15': {'1. open': '371.2800',
   '2. high': '373.1300',
   '3. low': '367.1100',
   '4. close': '369.6700',
   '5. volume': '26860095'},
  '2023-11-14': {'1. open': '371.0100',
   '2. high': '371.9500',
   '3. low': '367.3454',
   '4. close': '370.2700',
   '5. volume': '27683862'},
  '2023-11-13': {'1. open': '368.2200',
   '2. high': '368.4700',
   '3. low': '365.9000',
   '4. close': '366.6800',
   '5. volume': '19986506'},
  '2023-11-10': {'1. open': '361.4900',
   '2. high': '370.1000',
   '3. low': '361.0700',
   '4. close': '369.6700',
   '5. volume': '28065164'},
  '2023-11-09': {'1. open': '362.3000',
   '2. high': '364.7900',
   '3. low': '360.3620',
   '4. close': '360.6900',
   '5. volume': '24847331'},
  '2023-11-08': {'1. open': '361.6800',
   '2. high': '363.8700',
   '3. low': '360.5500',
   '4. close': '363.2000',
   '5. volume': '26767828'},
  '2023-11-07': {'1. open': '359.4000',
   '2. high': '362.4600',
   '3. low': '357.6300',
   '4. close': '360.5300',
   '5. volume': '25833931'},
  '2023-11-06': {'1. open': '353.4500',
   '2. high': '357.5400',
   '3. low': '353.3500',
   '4. close': '356.5300',
   '5. volume': '23828301'},
  '2023-11-03': {'1. open': '349.6300',
   '2. high': '354.3900',
   '3. low': '347.3300',
   '4. close': '352.8000',
   '5. volume': '23637673'},
  '2023-11-02': {'1. open': '347.2400',
   '2. high': '348.8300',
   '3. low': '344.7700',
   '4. close': '348.3200',
   '5. volume': '24348072'},
  '2023-11-01': {'1. open': '339.7900',
   '2. high': '347.4200',
   '3. low': '339.6500',
   '4. close': '346.0700',
   '5. volume': '28158819'},
  '2023-10-31': {'1. open': '338.8500',
   '2. high': '339.0000',
   '3. low': '334.6900',
   '4. close': '338.1100',
   '5. volume': '20265282'},
  '2023-10-30': {'1. open': '333.4100',
   '2. high': '339.4500',
   '3. low': '331.8300',
   '4. close': '337.3100',
   '5. volume': '22828082'},
  '2023-10-27': {'1. open': '330.4250',
   '2. high': '336.7200',
   '3. low': '328.4007',
   '4. close': '329.8100',
   '5. volume': '29856522'},
  '2023-10-26': {'1. open': '340.5400',
   '2. high': '341.6300',
   '3. low': '326.9400',
   '4. close': '327.8900',
   '5. volume': '37828543'},
  '2023-10-25': {'1. open': '345.0200',
   '2. high': '346.2000',
   '3. low': '337.6200',
   '4. close': '340.6700',
   '5. volume': '55053828'},
  '2023-10-24': {'1. open': '331.3000',
   '2. high': '331.8400',
   '3. low': '327.6000',
   '4. close': '330.5300',
   '5. volume': '31153571'},
  '2023-10-23': {'1. open': '325.4700',
   '2. high': '332.7250',
   '3. low': '324.3900',
   '4. close': '329.3200',
   '5. volume': '24374748'},
  '2023-10-20': {'1. open': '331.7200',
   '2. high': '331.9200',

In [130]:
# Extraer las fechas del JSON
dates = list(data_m['Time Series (Daily)'].keys())

# Crear un DataFrame de Pandas
data_mn = pd.DataFrame(dates, columns=['Fecha'])

# Imprimir el DataFrame
print(data_mn)

           Fecha
0     2024-05-03
1     2024-05-02
2     2024-05-01
3     2024-04-30
4     2024-04-29
...          ...
6161  1999-11-05
6162  1999-11-04
6163  1999-11-03
6164  1999-11-02
6165  1999-11-01

[6166 rows x 1 columns]

In [143]:
historical_quotes = []

for date, values in data_m["Time Series (Daily)"].items():
    # Verifica si la fecha es válida antes de crear un objeto Quote
    if date is not None:
        # Convertir la fecha de cadena a datetime
        date_datetime = datetime.strptime(date, "%Y-%m-%d")
        
        # Crear el objeto Quote
        quote = Quote(date=date_datetime, open=float(values["1. open"]), high=float(values["2. high"]),
                      low=float(values["3. low"]), close=float(values["4. close"]), volume=int(values["5. volume"]))
        
        # Agregar el objeto Quote a la lista de citas históricas
        historical_quotes.append(quote)

In [147]:
# fetch historical quotes from your feed (your method)
quotes = historical_quotes

# calculate 20-period SMA
results = indicators.get_sma(quotes, 20)

for r in results:
    print(f"SMA on {r.date.date()} was ${r.sma or 0:.4f}")

SMA on 1999-11-01 was $0.0000
SMA on 1999-11-02 was $0.0000
SMA on 1999-11-03 was $0.0000
SMA on 1999-11-04 was $0.0000
SMA on 1999-11-05 was $0.0000
SMA on 1999-11-08 was $0.0000
SMA on 1999-11-09 was $0.0000
SMA on 1999-11-10 was $0.0000
SMA on 1999-11-11 was $0.0000
SMA on 1999-11-12 was $0.0000
SMA on 1999-11-15 was $0.0000
SMA on 1999-11-16 was $0.0000
SMA on 1999-11-17 was $0.0000
SMA on 1999-11-18 was $0.0000
SMA on 1999-11-19 was $0.0000
SMA on 1999-11-22 was $0.0000
SMA on 1999-11-23 was $0.0000
SMA on 1999-11-24 was $0.0000
SMA on 1999-11-26 was $0.0000
SMA on 1999-11-29 was $7363.3000
SMA on 1999-11-30 was $7356.7000
SMA on 1999-12-01 was $7359.8500
SMA on 1999-12-02 was $7787.9000
SMA on 1999-12-03 was $7809.7500
SMA on 1999-12-06 was $7829.1500
SMA on 1999-12-07 was $7425.9500
SMA on 1999-12-08 was $7440.3500
SMA on 1999-12-09 was $7468.5000
SMA on 1999-12-10 was $7489.7500
SMA on 1999-12-13 was $7526.9000
SMA on 1999-12-14 was $7976.8500
SMA on 1999-12-15 was $8082.5000
SMA on 1999-12-16 was $8608.4500
SMA on 1999-12-17 was $8760.0000
SMA on 1999-12-20 was $9280.7500
SMA on 1999-12-21 was $9411.0500
SMA on 1999-12-22 was $9550.7500
SMA on 1999-12-23 was $9679.5000
SMA on 1999-12-27 was $9819.5000
SMA on 1999-12-28 was $9427.3000
SMA on 1999-12-29 was $9561.7500
SMA on 1999-12-30 was $9683.9000
SMA on 1999-12-31 was $9793.6000
SMA on 2000-01-03 was $9895.8000
SMA on 2000-01-04 was $9981.7000
SMA on 2000-01-05 was $10504.2500
SMA on 2000-01-06 was $10100.5000
SMA on 2000-01-07 was $10193.9500
SMA on 2000-01-10 was $10285.8500
SMA on 2000-01-11 was $10349.6000
SMA on 2000-01-12 was $10385.2000
SMA on 2000-01-13 was $10382.0500
SMA on 2000-01-14 was $10374.8500
SMA on 2000-01-18 was $10375.1500
SMA on 2000-01-19 was $9864.9000
SMA on 2000-01-20 was $9338.5500
SMA on 2000-01-21 was $9269.5000
SMA on 2000-01-24 was $9188.5500
SMA on 2000-01-25 was $9107.0000
SMA on 2000-01-26 was $9545.1000
SMA on 2000-01-27 was $9449.1500
SMA on 2000-01-28 was $9352.3000
SMA on 2000-01-31 was $9257.9000
SMA on 2000-02-01 was $9189.8000
SMA on 2000-02-02 was $9130.7500
SMA on 2000-02-03 was $9079.8000
SMA on 2000-02-04 was $9557.6000
SMA on 2000-02-07 was $9533.5000
SMA on 2000-02-08 was $9521.9500
SMA on 2000-02-09 was $9027.1000
SMA on 2000-02-10 was $8551.0500
SMA on 2000-02-11 was $8511.7000
SMA on 2000-02-14 was $8448.5500
SMA on 2000-02-15 was $8364.8000
SMA on 2000-02-16 was $8799.4000
SMA on 2000-02-17 was $9244.5000
SMA on 2000-02-18 was $9201.0500
SMA on 2000-02-22 was $9163.8500
SMA on 2000-02-23 was $9121.0500
SMA on 2000-02-24 was $9097.9500
SMA on 2000-02-25 was $9060.7500
SMA on 2000-02-28 was $9027.3000
SMA on 2000-02-29 was $8984.8000
SMA on 2000-03-01 was $8924.1500
SMA on 2000-03-02 was $8886.9500
SMA on 2000-03-03 was $8849.4500
SMA on 2000-03-06 was $8769.7500
SMA on 2000-03-07 was $8701.0000
SMA on 2000-03-08 was $8629.1000
SMA on 2000-03-09 was $8627.1000
SMA on 2000-03-10 was $8624.6000
SMA on 2000-03-13 was $8173.9000
SMA on 2000-03-14 was $8151.4000
SMA on 2000-03-15 was $8135.4500
SMA on 2000-03-16 was $8124.2000
SMA on 2000-03-17 was $8122.9500
SMA on 2000-03-20 was $8134.5000
SMA on 2000-03-21 was $8179.2000
SMA on 2000-03-22 was $8224.2000
SMA on 2000-03-23 was $8309.8000
SMA on 2000-03-24 was $8411.7000
SMA on 2000-03-27 was $8474.2000
SMA on 2000-03-28 was $8548.9000
SMA on 2000-03-29 was $8630.8000
SMA on 2000-03-30 was $8680.8000
SMA on 2000-03-31 was $8731.4500
SMA on 2000-04-03 was $8732.7000
SMA on 2000-04-04 was $8711.1500
SMA on 2000-04-05 was $8665.2000
SMA on 2000-04-06 was $8658.2000
SMA on 2000-04-07 was $9053.0000
SMA on 2000-04-10 was $9434.3000
SMA on 2000-04-11 was $9378.0500
SMA on 2000-04-12 was $9298.0500
SMA on 2000-04-13 was $9217.4500
SMA on 2000-04-14 was $9091.2000
SMA on 2000-04-17 was $8983.7000
SMA on 2000-04-18 was $8872.7500
SMA on 2000-04-19 was $8749.9500
SMA on 2000-04-20 was $8585.3000
SMA on 2000-04-24 was $8359.9500
SMA on 2000-04-25 was $8186.5000
SMA on 2000-04-26 was $7698.9500
SMA on 2000-04-27 was $7512.0500
SMA on 2000-04-28 was $7343.9500
SMA on 2000-05-01 was $7179.9000
SMA on 2000-05-02 was $7074.9000
SMA on 2000-05-03 was $6984.9000
SMA on 2000-05-04 was $6905.2500
SMA on 2000-05-05 was $7217.8500
SMA on 2000-05-08 was $7121.6000
SMA on 2000-05-09 was $7030.3500
SMA on 2000-05-10 was $6941.9500
SMA on 2000-05-11 was $6884.4500
SMA on 2000-05-12 was $6832.2500
SMA on 2000-05-15 was $6808.5000
SMA on 2000-05-16 was $6463.9000
SMA on 2000-05-17 was $6399.5500
SMA on 2000-05-18 was $6337.0500
SMA on 2000-05-19 was $6267.6500
SMA on 2000-05-22 was $6255.5000
SMA on 2000-05-23 was $6224.6000
SMA on 2000-05-24 was $6518.4000
SMA on 2000-05-25 was $6200.1000
SMA on 2000-05-26 was $6158.5500
SMA on 2000-05-30 was $6108.2500
SMA on 2000-05-31 was $6071.7000
SMA on 2000-06-01 was $6041.7000
SMA on 2000-06-02 was $6021.0500
SMA on 2000-06-05 was $5999.8000
SMA on 2000-06-06 was $5998.8500
SMA on 2000-06-07 was $5695.0500
SMA on 2000-06-08 was $5708.1500
SMA on 2000-06-09 was $5712.8500
SMA on 2000-06-12 was $5703.1500
SMA on 2000-06-13 was $5695.6500
SMA on 2000-06-14 was $5696.1500
SMA on 2000-06-15 was $5719.5500
SMA on 2000-06-16 was $5751.4000
SMA on 2000-06-19 was $5794.5500
SMA on 2000-06-20 was $5848.3000
SMA on 2000-06-21 was $5935.8000
SMA on 2000-06-22 was $6007.3500
SMA on 2000-06-23 was $6365.0500
SMA on 2000-06-26 was $6097.6000
SMA on 2000-06-27 was $6174.7500
SMA on 2000-06-28 was $6256.6500
SMA on 2000-06-29 was $6319.8000
SMA on 2000-06-30 was $6028.2500
SMA on 2000-07-03 was $5733.9000
SMA on 2000-07-05 was $5425.0500
SMA on 2000-07-06 was $5794.5000
SMA on 2000-07-07 was $5491.4500
SMA on 2000-07-10 was $5544.6000
SMA on 2000-07-11 was $5605.8500
SMA on 2000-07-12 was $5668.0500
SMA on 2000-07-13 was $6032.5000
SMA on 2000-07-14 was $6065.3500
SMA on 2000-07-17 was $6093.5000
SMA on 2000-07-18 was $5764.3000
SMA on 2000-07-19 was $5755.2000
SMA on 2000-07-20 was $5725.8000
SMA on 2000-07-21 was $5688.0000
SMA on 2000-07-24 was $5652.3500
SMA on 2000-07-25 was $5647.1000
SMA on 2000-07-26 was $5592.1000
SMA on 2000-07-27 was $5544.2500
SMA on 2000-07-28 was $5506.7500
SMA on 2000-07-31 was $5815.8000
SMA on 2000-08-01 was $6119.2500
SMA on 2000-08-02 was $6426.8500
SMA on 2000-08-03 was $6373.4000
SMA on 2000-08-04 was $6678.0000
SMA on 2000-08-07 was $6315.8000
SMA on 2000-08-08 was $6290.8000
SMA on 2000-08-09 was $6260.5000
SMA on 2000-08-10 was $6223.9000
SMA on 2000-08-11 was $6191.4000
SMA on 2000-08-14 was $6161.4000
SMA on 2000-08-15 was $6480.2500
SMA on 2000-08-16 was $6150.1500
SMA on 2000-08-17 was $6133.9000
SMA on 2000-08-18 was $5807.8500
SMA on 2000-08-21 was $5808.1500
SMA on 2000-08-22 was $6129.9000
SMA on 2000-08-23 was $6144.6000
SMA on 2000-08-24 was $6153.3500
SMA on 2000-08-25 was $6158.0000
SMA on 2000-08-28 was $6165.5000
SMA on 2000-08-29 was $6176.7500
SMA on 2000-08-30 was $5864.9000
SMA on 2000-08-31 was $5862.7000
SMA on 2000-09-01 was $5868.0500
SMA on 2000-09-05 was $6183.6500
SMA on 2000-09-06 was $6160.2500
SMA on 2000-09-07 was $6139.3000
SMA on 2000-09-08 was $6122.7500
SMA on 2000-09-11 was $6104.6000
SMA on 2000-09-12 was $6084.2500
SMA on 2000-09-13 was $6067.4000
SMA on 2000-09-14 was $6360.9500
SMA on 2000-09-15 was $6324.1000
SMA on 2000-09-18 was $6320.1000
SMA on 2000-09-19 was $5999.5000
SMA on 2000-09-20 was $5964.5000
SMA on 2000-09-21 was $5931.7000
SMA on 2000-09-22 was $5892.3500
SMA on 2000-09-25 was $5845.5000
SMA on 2000-09-26 was $5802.4000
SMA on 2000-09-27 was $5750.8500
SMA on 2000-09-28 was $6022.4000
SMA on 2000-09-29 was $5974.9000
SMA on 2000-10-02 was $5919.6000
SMA on 2000-10-03 was $5851.8000
SMA on 2000-10-04 was $5781.8000
SMA on 2000-10-05 was $5708.4000
SMA on 2000-10-06 was $5639.6500
SMA on 2000-10-09 was $5566.5500
SMA on 2000-10-10 was $5498.7500
SMA on 2000-10-11 was $5436.2500
SMA on 2000-10-12 was $5379.1000
SMA on 2000-10-13 was $5326.9000
SMA on 2000-10-16 was $5547.3000
SMA on 2000-10-17 was $5767.0000
SMA on 2000-10-18 was $5704.5000
SMA on 2000-10-19 was $5692.9500
SMA on 2000-10-20 was $5702.6500
SMA on 2000-10-23 was $5707.0500
SMA on 2000-10-24 was $5424.3500
SMA on 2000-10-25 was $5427.4500
SMA on 2000-10-26 was $5443.1000
SMA on 2000-10-27 was $5480.0000
SMA on 2000-10-30 was $5529.6500
SMA on 2000-10-31 was $5591.2000
SMA on 2000-11-01 was $5662.1000
SMA on 2000-11-02 was $5736.7500
SMA on 2000-11-03 was $5800.2000
SMA on 2000-11-06 was $5564.0000
SMA on 2000-11-07 was $5326.4500
SMA on 2000-11-08 was $5394.9000
SMA on 2000-11-09 was $5477.3500
SMA on 2000-11-10 was $5545.4500
SMA on 2000-11-13 was $5625.7500
SMA on 2000-11-14 was $5717.6000
SMA on 2000-11-15 was $5809.1500
SMA on 2000-11-16 was $5844.4500
SMA on 2000-11-17 was $5863.8000
SMA on 2000-11-20 was $5889.1000
SMA on 2000-11-21 was $6197.1000
SMA on 2000-11-22 was $6232.1000
SMA on 2000-11-24 was $6259.6000
SMA on 2000-11-27 was $6274.6000
SMA on 2000-11-28 was $5962.8000
SMA on 2000-11-29 was $5943.7500
SMA on 2000-11-30 was $5882.5500
SMA on 2000-12-01 was $5814.1500
SMA on 2000-12-04 was $5755.1000
SMA on 2000-12-05 was $6019.7500
SMA on 2000-12-06 was $6267.9500
SMA on 2000-12-07 was $6186.4000
SMA on 2000-12-08 was $6104.2500
SMA on 2000-12-11 was $6057.7000
SMA on 2000-12-12 was $6017.4000
SMA on 2000-12-13 was $5959.6000
SMA on 2000-12-14 was $5637.0500
SMA on 2000-12-15 was $5538.3000
SMA on 2000-12-18 was $5432.0500
SMA on 2000-12-19 was $5320.1500
SMA on 2000-12-20 was $5002.1500
SMA on 2000-12-21 was $4878.1000
SMA on 2000-12-22 was $4760.6000
SMA on 2000-12-26 was $4641.5500
SMA on 2000-12-27 was $4840.2500
SMA on 2000-12-28 was $4737.7500
SMA on 2000-12-29 was $4667.7500
SMA on 2001-01-02 was $4601.5000
SMA on 2001-01-03 was $4559.0000
SMA on 2001-01-04 was $4501.8000
SMA on 2001-01-05 was $4464.0000
SMA on 2001-01-08 was $4443.0500
SMA on 2001-01-09 was $4429.9000
SMA on 2001-01-10 was $4404.0000
SMA on 2001-01-11 was $4139.6000
SMA on 2001-01-12 was $3880.1000
SMA on 2001-01-16 was $4115.1500
SMA on 2001-01-17 was $4133.9000
SMA on 2001-01-18 was $3922.6000
SMA on 2001-01-19 was $3729.0500
SMA on 2001-01-22 was $4008.9500
SMA on 2001-01-23 was $4094.5500
SMA on 2001-01-24 was $4177.0500
SMA on 2001-01-25 was $4251.7000
SMA on 2001-01-26 was $4051.5000
SMA on 2001-01-29 was $3860.9500
SMA on 2001-01-30 was $3960.9500
SMA on 2001-01-31 was $4049.3500
SMA on 2001-02-01 was $4121.5500
SMA on 2001-02-02 was $4183.4000
SMA on 2001-02-05 was $4247.4500
SMA on 2001-02-06 was $4315.5500
SMA on 2001-02-07 was $4379.9500
SMA on 2001-02-08 was $4426.8000
SMA on 2001-02-09 was $4694.9500
SMA on 2001-02-12 was $4961.9500
SMA on 2001-02-13 was $4990.1000
SMA on 2001-02-14 was $5017.3000
SMA on 2001-02-15 was $5283.6000
SMA on 2001-02-16 was $5539.6500
SMA on 2001-02-20 was $5518.4000
SMA on 2001-02-21 was $5496.8500
SMA on 2001-02-22 was $5458.1000
SMA on 2001-02-23 was $5432.8000
SMA on 2001-02-26 was $5698.6000
SMA on 2001-02-27 was $5963.2500
SMA on 2001-02-28 was $5675.8500
SMA on 2001-03-01 was $5667.3500
SMA on 2001-03-02 was $5638.9000
SMA on 2001-03-05 was $5622.0500
SMA on 2001-03-06 was $5609.5500
SMA on 2001-03-07 was $5600.2000
SMA on 2001-03-08 was $5573.0000
SMA on 2001-03-09 was $5545.2000
SMA on 2001-03-12 was $5509.2500
SMA on 2001-03-13 was $5486.4500
SMA on 2001-03-14 was $5222.5000
SMA on 2001-03-15 was $5199.0500
SMA on 2001-03-16 was $5177.8000
SMA on 2001-03-19 was $5162.8000
SMA on 2001-03-20 was $5146.8500
SMA on 2001-03-21 was $5115.9000
SMA on 2001-03-22 was $4866.9500
SMA on 2001-03-23 was $4866.0000
SMA on 2001-03-26 was $4848.5000
SMA on 2001-03-27 was $4842.8500
SMA on 2001-03-28 was $5091.1500
SMA on 2001-03-29 was $5071.2500
SMA on 2001-03-30 was $5061.2500
SMA on 2001-04-02 was $5053.1000
SMA on 2001-04-03 was $5022.8000
SMA on 2001-04-04 was $4979.0500
SMA on 2001-04-05 was $4966.5500
SMA on 2001-04-06 was $4964.0500
SMA on 2001-04-09 was $4990.1000
SMA on 2001-04-10 was $5017.5500
SMA on 2001-04-11 was $5290.7500
SMA on 2001-04-12 was $5333.2000
SMA on 2001-04-16 was $5364.3500
SMA on 2001-04-17 was $5400.2000
SMA on 2001-04-18 was $5463.9000
SMA on 2001-04-19 was $5553.8000
SMA on 2001-04-20 was $5561.3000
SMA on 2001-04-23 was $5619.7500
SMA on 2001-04-24 was $5677.2000
SMA on 2001-04-25 was $5734.4000
SMA on 2001-04-26 was $5802.2500
SMA on 2001-04-27 was $5860.9500
SMA on 2001-04-30 was $5926.2500
SMA on 2001-05-01 was $5998.0500
SMA on 2001-05-02 was $6079.9500
SMA on 2001-05-03 was $6162.9000
SMA on 2001-05-04 was $6232.9000
SMA on 2001-05-07 was $6308.8500
SMA on 2001-05-08 was $6383.4000
SMA on 2001-05-09 was $6120.2000
SMA on 2001-05-10 was $5855.0000
SMA on 2001-05-11 was $5578.8000
SMA on 2001-05-14 was $5618.4500
SMA on 2001-05-15 was $5652.4000
SMA on 2001-05-16 was $5671.0500
SMA on 2001-05-17 was $5671.7000
SMA on 2001-05-18 was $5977.6500
SMA on 2001-05-21 was $5980.3500
SMA on 2001-05-22 was $5994.1500
SMA on 2001-05-23 was $5680.5500
SMA on 2001-05-24 was $5693.5000
SMA on 2001-05-25 was $5712.4500
SMA on 2001-05-29 was $5725.4000
SMA on 2001-05-30 was $5720.5000
SMA on 2001-05-31 was $5717.6000
SMA on 2001-06-01 was $5726.6500
SMA on 2001-06-04 was $5726.8000
SMA on 2001-06-05 was $5406.2000
SMA on 2001-06-06 was $5407.7000
SMA on 2001-06-07 was $5740.9000
SMA on 2001-06-08 was $6071.8500
SMA on 2001-06-11 was $6397.7500
SMA on 2001-06-12 was $6414.5500
SMA on 2001-06-13 was $6426.6500
SMA on 2001-06-14 was $6115.3000
SMA on 2001-06-15 was $6114.5500
SMA on 2001-06-18 was $6108.5000
SMA on 2001-06-19 was $6101.1500
SMA on 2001-06-20 was $6096.6500
SMA on 2001-06-21 was $6411.0000
SMA on 2001-06-22 was $6396.5500
SMA on 2001-06-25 was $6386.2500
SMA on 2001-06-26 was $6385.2500
SMA on 2001-06-27 was $6395.0000
SMA on 2001-06-28 was $6412.8000
SMA on 2001-06-29 was $6097.6000
SMA on 2001-07-02 was $5779.0000
SMA on 2001-07-03 was $6095.0500
SMA on 2001-07-05 was $6075.8000
SMA on 2001-07-06 was $6037.7000
SMA on 2001-07-09 was $6000.2000
SMA on 2001-07-10 was $5962.0000
SMA on 2001-07-11 was $5634.8500
SMA on 2001-07-12 was $5317.2000
SMA on 2001-07-13 was $5639.4500
SMA on 2001-07-16 was $5655.2500
SMA on 2001-07-17 was $5679.9500
SMA on 2001-07-18 was $5696.2000
SMA on 2001-07-19 was $5712.0000
SMA on 2001-07-20 was $5708.7000
SMA on 2001-07-23 was $5700.0000
SMA on 2001-07-24 was $5687.3500
SMA on 2001-07-25 was $5674.0500
SMA on 2001-07-26 was $5651.3000
SMA on 2001-07-27 was $5614.9500
SMA on 2001-07-30 was $5611.3500
SMA on 2001-07-31 was $5907.0000
SMA on 2001-08-01 was $5887.0000
SMA on 2001-08-02 was $5881.7000
SMA on 2001-08-03 was $5885.8500
SMA on 2001-08-06 was $5888.0500
SMA on 2001-08-07 was $5897.4000
SMA on 2001-08-08 was $6188.4500
SMA on 2001-08-09 was $6477.7000
SMA on 2001-08-10 was $6448.6000
SMA on 2001-08-13 was $6421.8500
SMA on 2001-08-14 was $6386.2000
SMA on 2001-08-15 was $6064.9500
SMA on 2001-08-16 was $6025.2000
SMA on 2001-08-17 was $5988.7000
SMA on 2001-08-20 was $5684.6000
SMA on 2001-08-21 was $5656.9000
SMA on 2001-08-22 was $5622.8000
SMA on 2001-08-23 was $5585.4500
SMA on 2001-08-24 was $5568.3500
SMA on 2001-08-27 was $5847.0000
SMA on 2001-08-28 was $5819.7500
SMA on 2001-08-29 was $5788.6500
SMA on 2001-08-30 was $5736.1000
SMA on 2001-08-31 was $5686.9000
SMA on 2001-09-04 was $5384.3000
SMA on 2001-09-05 was $5341.2500
SMA on 2001-09-06 was $5297.0500
SMA on 2001-09-07 was $4999.7000
SMA on 2001-09-10 was $4960.0000
SMA on 2001-09-17 was $4895.4000
SMA on 2001-09-18 was $4843.5500
SMA on 2001-09-19 was $5081.3000
SMA on 2001-09-20 was $5012.0000
SMA on 2001-09-21 was $4951.1500
SMA on 2001-09-24 was $5179.8500
SMA on 2001-09-25 was $4901.6000
SMA on 2001-09-26 was $4849.6500
SMA on 2001-09-27 was $4803.8500
SMA on 2001-09-28 was $4749.4500
SMA on 2001-10-01 was $4696.8500
SMA on 2001-10-02 was $4658.4000
SMA on 2001-10-03 was $4638.3000
SMA on 2001-10-04 was $4635.8000
SMA on 2001-10-05 was $4639.1500
SMA on 2001-10-08 was $4901.3000
SMA on 2001-10-09 was $4885.4000
SMA on 2001-10-10 was $4882.8500
SMA on 2001-10-11 was $5136.7500
SMA on 2001-10-12 was $5130.7500
SMA on 2001-10-15 was $5156.5000
SMA on 2001-10-16 was $5177.1500
SMA on 2001-10-17 was $5187.9500
SMA on 2001-10-18 was $5217.9000
SMA on 2001-10-19 was $4998.3000
SMA on 2001-10-22 was $5039.0500
SMA on 2001-10-23 was $5315.5500
SMA on 2001-10-24 was $5370.8000
SMA on 2001-10-25 was $5433.8000
SMA on 2001-10-26 was $5209.0500
SMA on 2001-10-29 was $5248.3000
SMA on 2001-10-30 was $5277.4500
SMA on 2001-10-31 was $5287.0500
SMA on 2001-11-01 was $5314.0500
SMA on 2001-11-02 was $5056.1500
SMA on 2001-11-05 was $5082.3000
SMA on 2001-11-06 was $5133.4000
SMA on 2001-11-07 was $5177.1000
SMA on 2001-11-08 was $5217.6000
SMA on 2001-11-09 was $5261.7500
SMA on 2001-11-12 was $5300.4000
SMA on 2001-11-13 was $5042.1000
SMA on 2001-11-14 was $5091.7000
SMA on 2001-11-15 was $5138.5500
SMA on 2001-11-16 was $5438.3500
SMA on 2001-11-19 was $5470.2500
SMA on 2001-11-20 was $5200.8000
SMA on 2001-11-21 was $5214.4500
SMA on 2001-11-23 was $5225.2000
SMA on 2001-11-26 was $5519.8000
SMA on 2001-11-27 was $5540.3000
SMA on 2001-11-28 was $5277.3000
SMA on 2001-11-29 was $5310.7500
SMA on 2001-11-30 was $5322.6000
SMA on 2001-12-03 was $5615.7500
SMA on 2001-12-04 was $5332.4000
SMA on 2001-12-05 was $5042.5500
SMA on 2001-12-06 was $5064.5500
SMA on 2001-12-07 was $5081.6000
SMA on 2001-12-10 was $5090.8500
SMA on 2001-12-11 was $5098.5000
SMA on 2001-12-12 was $5404.3000
SMA on 2001-12-13 was $5405.9000
SMA on 2001-12-14 was $5412.5000
SMA on 2001-12-17 was $5428.6500
SMA on 2001-12-18 was $5442.3000
SMA on 2001-12-19 was $5757.0500
SMA on 2001-12-20 was $5770.6000
SMA on 2001-12-21 was $5784.7500
SMA on 2001-12-24 was $5795.4000
SMA on 2001-12-26 was $5815.1000
SMA on 2001-12-27 was $6122.9500
SMA on 2001-12-28 was $6138.1000
SMA on 2001-12-31 was $6148.3000
SMA on 2002-01-02 was $6159.6500
SMA on 2002-01-03 was $6472.8000
SMA on 2002-01-04 was $6473.2000
SMA on 2002-01-07 was $6472.7500
SMA on 2002-01-08 was $6480.5000
SMA on 2002-01-09 was $6488.7500
SMA on 2002-01-10 was $6498.5500
SMA on 2002-01-11 was $6501.8500
SMA on 2002-01-14 was $6512.8500
SMA on 2002-01-15 was $6523.4000
SMA on 2002-01-16 was $6517.8500
SMA on 2002-01-17 was $6520.8000
SMA on 2002-01-18 was $6206.4000
SMA on 2002-01-22 was $6194.9000
SMA on 2002-01-23 was $6175.9000
SMA on 2002-01-24 was $5871.8500
SMA on 2002-01-25 was $5565.3500
SMA on 2002-01-28 was $5545.2000
SMA on 2002-01-29 was $5517.4500
SMA on 2002-01-30 was $5500.4500
SMA on 2002-01-31 was $5483.8000
SMA on 2002-02-01 was $5450.9500
SMA on 2002-02-04 was $5722.1000
SMA on 2002-02-05 was $5685.0500
SMA on 2002-02-06 was $5368.3500
SMA on 2002-02-07 was $5054.7000
SMA on 2002-02-08 was $5011.5500
SMA on 2002-02-11 was $4974.1500
SMA on 2002-02-12 was $4932.5000
SMA on 2002-02-13 was $4893.8500
SMA on 2002-02-14 was $4862.9000
SMA on 2002-02-15 was $4814.7500
SMA on 2002-02-19 was $5076.3500
SMA on 2002-02-20 was $4784.0000
SMA on 2002-02-21 was $4755.5500
SMA on 2002-02-22 was $5013.2000
SMA on 2002-02-25 was $5276.7000
SMA on 2002-02-26 was $5250.3500
SMA on 2002-02-27 was $5230.7000
SMA on 2002-02-28 was $5208.1500
SMA on 2002-03-01 was $5196.4500
SMA on 2002-03-04 was $4914.8000
SMA on 2002-03-05 was $4924.6000
SMA on 2002-03-06 was $4937.0000
SMA on 2002-03-07 was $5220.4000
SMA on 2002-03-08 was $5510.2500
SMA on 2002-03-11 was $5528.7000
SMA on 2002-03-12 was $5535.7500
SMA on 2002-03-13 was $5266.1000
SMA on 2002-03-14 was $5263.1000
SMA on 2002-03-15 was $5267.1500
SMA on 2002-03-18 was $5276.7000
SMA on 2002-03-19 was $5293.2000
SMA on 2002-03-20 was $5293.3000
SMA on 2002-03-21 was $5309.8500
SMA on 2002-03-22 was $5322.1500
SMA on 2002-03-25 was $5322.9000
SMA on 2002-03-26 was $5325.5500
SMA on 2002-03-27 was $5330.8000
SMA on 2002-03-28 was $5340.6500
SMA on 2002-04-01 was $5335.7000
SMA on 2002-04-02 was $5590.4500
SMA on 2002-04-03 was $5556.7000
SMA on 2002-04-04 was $5520.8000

In [139]:
def obtener_historical_quotes(symbol, data):
    data_m['Meta Data']['2. Symbol'] == symbol
    historical_quotes = []

    for date, values in data["Time Series (Daily)"].items():
        # Verificar si la fecha es válida antes de crear un objeto Quote
        if date is not None:
            # Convertir la fecha de cadena a datetime
            date_datetime = datetime.strptime(date, "%Y-%m-%d")
            
            # Crear el objeto Quote
            quote = Quote(symbol=symbol, date=date_datetime, open=float(values["1. open"]), high=float(values["2. high"]),
                          low=float(values["3. low"]), close=float(values["4. close"]), volume=int(values["5. volume"]))
            
            # Agregar el objeto Quote a la lista de citas históricas
            historical_quotes.append(quote)
    
    return historical_quotes

In [142]:
data_m['Meta Data']['2. Symbol']

'MSFT'

In [140]:
obtener_historical_quotes("MSFT", data_m)

TypeError: _Quote.__init__() got an unexpected keyword argument 'symbol'

In [ ]:
# fetch historical quotes from your feed (your method)
quotes = get_historical_quotes("MSFT")

# calculate 20-period SMA
results = indicators.get_sma(quotes, 20)

# use results as needed for your use case (example only)
for r in results:
    print(f"SMA on {r.date.date()} was ${r.sma or 0:.4f}")

In [129]:
# Crear una instancia de la clase _Quote para cada conjunto de datos
quotes = []
for date, values in data_m['Time Series (Daily)'].items():
    # Crear una instancia de _Quote con los valores correspondientes
    quote = _Quote()
    quote.date = date
    quote.open = float(values['1. open'])
    quote.high = float(values['2. high'])
    quote.low = float(values['3. low'])
    quote.close = float(values['4. close'])
    quote.volume = int(values['5. volume'])
    
    # Agregar la instancia a la lista de cotizaciones
    quotes.append(quote)

# Calcular RSI(14)
rsi_14 = indicators.get_rsi([quote.close for quote in quotes], 14)

print("RSI(14):", rsi_14)

TypeError: _Quote.__init__() missing 1 required positional argument: 'date'

In [113]:
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta
import matplotlib.dates as mdates
from datetime import datetime, timedelta

# Define the stock symbol and timeframe
symbol = 'DIS'
end_date = datetime.today()
start_date = end_date - timedelta(days=120)  # 4 months before today

# Fetch stock data using yfinance
stock_data = yf.download(symbol, start=start_date, end=end_date)

# Calculate technical indicators using pandas-ta
stock_data.ta.macd(append=True)
stock_data.ta.rsi(append=True)
stock_data.ta.bbands(append=True)
stock_data.ta.obv(append=True)

# Calculate additional technical indicators
stock_data.ta.sma(length=20, append=True)
stock_data.ta.ema(length=50, append=True)
stock_data.ta.stoch(append=True)
stock_data.ta.adx(append=True)

# Calculate other indicators
stock_data.ta.willr(append=True)
stock_data.ta.cmf(append=True)
stock_data.ta.psar(append=True)

#convert OBV to million
stock_data['OBV_in_million'] =  stock_data['OBV']/1e7
stock_data['MACD_histogram_12_26_9'] =  stock_data['MACDh_12_26_9'] # not to confuse chatGTP

# Summarize technical indicators for the last day
last_day_summary = stock_data.iloc[-1][['Adj Close',
    'MACD_12_26_9','MACD_histogram_12_26_9', 'RSI_14', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0','SMA_20', 'EMA_50','OBV_in_million', 'STOCHk_14_3_3', 
    'STOCHd_14_3_3', 'ADX_14',  'WILLR_14', 'CMF_20', 
    'PSARl_0.02_0.2', 'PSARs_0.02_0.2'
]]

print("Summary of Technical Indicators for the Last Day:")
print(last_day_summary)

[*********************100%%**********************]  1 of 1 completed

Summary of Technical Indicators for the Last Day:
Adj Close                 113.660004
MACD_12_26_9               -0.703076
MACD_histogram_12_26_9     -0.219685
RSI_14                     50.242026
BBL_5_2.0                 109.749058
BBM_5_2.0                 111.988002
BBU_5_2.0                 114.226946
SMA_20                    113.677000
EMA_50                    111.626322
OBV_in_million             15.739781
STOCHk_14_3_3              43.237035
STOCHd_14_3_3              24.913433
ADX_14                     23.731984
WILLR_14                  -19.580330
CMF_20                     -0.053737
PSARl_0.02_0.2            110.209999
PSARs_0.02_0.2                   NaN
Name: 2024-05-03 00:00:00, dtype: float64

In [116]:
import yfinance as yf

msft = yf.Ticker("MSFT")

# get all stock info
msft.info

# get historical market data
hist = msft.history(period="1mo")

# show meta information about the history (requires history() to be called first)
msft.history_metadata

# show actions (dividends, splits, capital gains)
msft.actions
msft.dividends
msft.splits
msft.capital_gains  # only for mutual funds & etfs

# show share count
msft.get_shares_full(start="2022-01-01", end=None)

# show financials:
# - income statement
msft.income_stmt
msft.quarterly_income_stmt
# - balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet
# - cash flow statement
msft.cashflow
msft.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

# show holders
msft.major_holders
msft.institutional_holders
msft.mutualfund_holders
msft.insider_transactions
msft.insider_purchases
msft.insider_roster_holders

# show recommendations
msft.recommendations
msft.recommendations_summary
msft.upgrades_downgrades

# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

# show options expirations
msft.options

# show news
msft.news

# get option chain for specific expiration
opt = msft.option_chain('2024-05-10')
# data available via: opt.calls, opt.puts

In [119]:
msft.balance_sheet

,2023-06-30,2022-06-30,2021-06-30,2020-06-30
Ordinary Shares Number,7432000000.0,7464000000.0,7519000000.0,7571000000.0
Share Issued,7432000000.0,7464000000.0,7519000000.0,7571000000.0
Net Debt,12533000000.0,35850000000.0,43922000000.0,49751000000.0
Total Debt,59965000000.0,61270000000.0,67775000000.0,70998000000.0
Tangible Book Value,128971000000.0,87720000000.0,84477000000.0,67915000000.0
...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,111256000000.0,104749000000.0,130256000000.0,136527000000.0
Other Short Term Investments,76552000000.0,90818000000.0,116032000000.0,122951000000.0
Cash And Cash Equivalents,34704000000.0,13931000000.0,14224000000.0,13576000000.0
Cash Equivalents,26226000000.0,5673000000.0,6952000000.0,7666000000.0
Cash Financial,8478000000.0,8258000000.0,7272000000.0,5910000000.0

In [122]:
from stock_indicators import indicators

# fetch historical quotes from your feed (your method)
quotes = quote.get_historical_quotes("MSFT")

# calculate 20-period SMA
results = indicators.get_sma(quotes, 20)

# use results as needed for your use case (example only)
for r in results:
    print(f"SMA on {r.date.date()} was ${r.sma or 0:.4f}")

AttributeError: type object '_Quote' has no attribute 'get_historical_quotes'